monolog:
    handlers:
        doctrine:
            type: service
            id: app.utils.doctrine_handler
            level: debug
            channels: ["app"]


        file_log:
            type: stream
            path: "%kernel.logs_dir%/custom.log"
            level: debug
            channels: ["app"]


        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]


        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
